# Generated by Django 4.2.5 on 2023-09-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='status',
            field=models.CharField(choices=[('ok', 'Successfully'), ('failed', 'Error')], default='ok', max_length=50, verbose_name='status'),
        ),
    ]
