# Generated by Django 4.2.5 on 2023-09-28 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_alter_mailingsettings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='mailing.serviceclient', verbose_name='client'),
        ),
    ]
