# Generated by Django 4.2.5 on 2023-09-23 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(upload_to='media/', verbose_name='image')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_of_publication')),
            ],
        ),
    ]
